"""
Canonical catalog of the REST calls the wizard makes — the single source of
truth for both the in-app curl docs (lib.help_docs) and the downloadable
Postman collection (lib.postman). Grounded in the actual client code; keep it in
sync if endpoints change.

Placeholders use Postman ``{{var}}`` syntax so the same strings drop straight
into a Postman environment; the curl renderer shows them verbatim for you to
substitute.
"""

# Environment variables surfaced in the Postman collection.
VARIABLES = [
    ("aos8_host", "10.0.0.1", "Mobility Controller/Conductor IP (port 4343)"),
    ("uidaruba", "", "AOS 8 session token from /v1/api/login"),
    ("config_path", "/md", "/md on a Conductor, /mm/mynode on a standalone MC"),
    ("central_base", "https://us4.api.central.arubanetworks.com", "New Central regional API base"),
    ("classic_base", "https://apigw-uswest4.central.arubanetworks.com", "Classic API gateway base"),
    ("glp_base", "https://global.api.greenlake.hpe.com", "GreenLake global API base"),
    ("client_id", "", "GreenLake API client id (New Central + GLP)"),
    ("client_secret", "", "GreenLake API client secret"),
    ("central_token", "", "Bearer token from the GreenLake SSO token call"),
    ("glp_token", "", "Bearer token for GLP (same SSO call/creds)"),
    ("classic_token", "", "Classic API gateway access token (~2h)"),
    ("classic_refresh_token", "", "Classic refresh token (rotates on every use)"),
    ("vlan_id", "100", "VLAN id"),
    ("ssid_name", "Corp", "SSID / wlan-ssid name"),
    ("group", "ap-group-1", "Device group / AP group name"),
    ("serial", "CNABC12345", "AP serial number"),
    ("device_uuid", "", "GLP device UUID (resolve from serial first)"),
    ("op_id", "", "GLP async-operation id"),
]

# Each request: name, method, url, headers, body, desc.
# body: None | {"mode":"urlencoded","data":{...}} | {"mode":"raw","data": <str|dict>}
GROUPS = [
    {
        "name": "AOS 8 — source pull",
        "blurb": "Live REST pull from the Mobility Controller (port 4343). TLS is "
                 "self-signed, hence curl -k. The login returns a UIDARUBA token "
                 "used as a query param on every later call.",
        "requests": [
            {"name": "Login", "method": "POST",
             "url": "https://{{aos8_host}}:4343/v1/api/login",
             "headers": {}, "desc": "Returns _global_result.UIDARUBA on success (status 0).",
             "body": {"mode": "urlencoded", "data": {"username": "admin", "password": "{{password}}"}}},
            {"name": "Get config object (ap_group)", "method": "GET",
             "url": "https://{{aos8_host}}:4343/v1/configuration/object/ap_group?UIDARUBA={{uidaruba}}&config_path={{config_path}}",
             "headers": {}, "body": None,
             "desc": "Swap ap_group for ssid_prof, wlan_virtual_ap, vlan_id, rad_server, server_group_prof, node_hierarchy."},
            {"name": "Show command", "method": "GET",
             "url": "https://{{aos8_host}}:4343/v1/configuration/showcommand?command=show version&UIDARUBA={{uidaruba}}&config_path={{config_path}}",
             "headers": {}, "body": None,
             "desc": "e.g. show version, show controller-ip, show lc-cluster group-membership, show ap database long."},
        ],
    },
    {
        "name": "GreenLake — auth",
        "blurb": "Client-credentials token used for BOTH New Central and GLP. The "
                 "API client must carry Aruba Central AND GreenLake scopes.",
        "requests": [
            {"name": "SSO token (client_credentials)", "method": "POST",
             "url": "https://sso.common.cloud.hpe.com/as/token.oauth2",
             "headers": {}, "desc": "Response access_token -> use as Bearer for New Central + GLP.",
             "body": {"mode": "urlencoded", "data": {
                 "grant_type": "client_credentials",
                 "client_id": "{{client_id}}", "client_secret": "{{client_secret}}"}}},
        ],
    },
    {
        "name": "New Central — provision + validate",
        "blurb": "Config writes and monitoring reads against your regional base. "
                 "Bearer {{central_token}}.",
        "requests": [
            {"name": "Get scope-maps (global scope)", "method": "GET",
             "url": "{{central_base}}/network-config/v1/scope-maps",
             "headers": {"Authorization": "Bearer {{central_token}}"}, "body": None,
             "desc": "Resolve the SERVICE_PERSONA scope-id used by every later create."},
            {"name": "List sites", "method": "GET",
             "url": "{{central_base}}/network-config/v1alpha1/sites",
             "headers": {"Authorization": "Bearer {{central_token}}"}, "body": None,
             "desc": "Fallbacks: /network-config/v1/sites then /network-monitoring/v1/sites."},
            {"name": "List device groups", "method": "GET",
             "url": "{{central_base}}/network-config/v1/device-groups",
             "headers": {"Authorization": "Bearer {{central_token}}"}, "body": None},
            {"name": "Create device group", "method": "POST",
             "url": "{{central_base}}/network-config/v1/device-groups",
             "headers": {"Authorization": "Bearer {{central_token}}"},
             "body": {"mode": "raw", "data": {"scopeName": "{{group}}"}},
             "desc": "API_ACCESS_RESTRICTED here means a hybrid tenant — route group create/move via Classic."},
            {"name": "Create VLAN (layer2-vlan)", "method": "POST",
             "url": "{{central_base}}/network-config/v1/layer2-vlan/{{vlan_id}}",
             "headers": {"Authorization": "Bearer {{central_token}}"},
             "body": {"mode": "raw", "data": {"id": "{{vlan_id}}"}},
             "desc": "PUT on duplicate; then scope-map it to the group."},
            {"name": "Create SSID (wlan-ssid)", "method": "POST",
             "url": "{{central_base}}/network-config/v1/wlan-ssids/{{ssid_name}}",
             "headers": {"Authorization": "Bearer {{central_token}}"},
             "body": {"mode": "raw", "data": {"ssid-name": "{{ssid_name}}", "forward-mode": "FORWARD_MODE_BRIDGE"}},
             "desc": "Bridge = underlay; tunnel uses FORWARD_MODE_L2 + an overlay-wlan binding."},
            {"name": "Create overlay-wlan (tunnel SSID -> GW cluster)", "method": "POST",
             "url": "{{central_base}}/network-config/v1/overlay-wlan/{{ssid_name}}",
             "headers": {"Authorization": "Bearer {{central_token}}"},
             "body": {"mode": "raw", "data": {"ssid": "{{ssid_name}}"}}},
            {"name": "Create scope-map (bind resource->scope)", "method": "POST",
             "url": "{{central_base}}/network-config/v1/scope-maps",
             "headers": {"Authorization": "Bearer {{central_token}}"},
             "body": {"mode": "raw", "data": {"scope-map": [{"scope-name": "{{group}}", "scope-id": 0, "persona": "CAMPUS_AP", "resource": "wlan-ssids/{{ssid_name}}"}]}}},
            {"name": "Set firmware compliance", "method": "POST",
             "url": "{{central_base}}/network-config/v1alpha1/firmware-compliance",
             "headers": {"Authorization": "Bearer {{central_token}}"},
             "body": {"mode": "raw", "data": {"scope-id": 0, "device-function": "ACCESS_POINT"}}},
            {"name": "Move APs into group (cutover)", "method": "POST",
             "url": "{{central_base}}/network-config/v1/device-groups-add-devices",
             "headers": {"Authorization": "Bearer {{central_token}}"},
             "body": {"mode": "raw", "data": {"desScopeId": "{{group_scope_id}}", "devices": ["{{serial}}"]}},
             "desc": "The conversion trigger — APs reboot into AOS 10 (~10-20 min offline)."},
            {"name": "Assign CAMPUS_AP persona", "method": "POST",
             "url": "{{central_base}}/network-config/v1alpha1/persona-assignment",
             "headers": {"Authorization": "Bearer {{central_token}}"},
             "body": {"mode": "raw", "data": {"persona-device-list": [{"device-function": "CAMPUS_AP", "device-id": ["{{serial}}"]}]}}},
            {"name": "Assign APs to site", "method": "POST",
             "url": "{{central_base}}/network-config/v1/site-add-devices",
             "headers": {"Authorization": "Bearer {{central_token}}"},
             "body": {"mode": "raw", "data": {"desScopeId": "{{site_scope_id}}", "devices": ["{{serial}}"]}}},
            {"name": "List devices (validate online)", "method": "GET",
             "url": "{{central_base}}/network-monitoring/v1/devices?limit=100&offset=0",
             "headers": {"Authorization": "Bearer {{central_token}}"}, "body": None,
             "desc": "Filter deviceType in ACCESS_POINT/AP/IAP; status 'up' = online."},
        ],
    },
    {
        "name": "GreenLake — devices & subscriptions (GLP)",
        "blurb": "Claim + subscribe so Central adopts the APs. Bearer {{glp_token}}.",
        "requests": [
            {"name": "List workspace devices", "method": "GET",
             "url": "{{glp_base}}/devices/v1/devices?limit=100&offset=0",
             "headers": {"Authorization": "Bearer {{glp_token}}"}, "body": None,
             "desc": "Add ?filter=serialNumber eq '{{serial}}' to resolve one device UUID."},
            {"name": "Claim devices", "method": "POST",
             "url": "{{glp_base}}/devices/v1/devices",
             "headers": {"Authorization": "Bearer {{glp_token}}"},
             "body": {"mode": "raw", "data": {"network": [{"serialNumber": "{{serial}}", "macAddress": "aa:bb:cc:dd:ee:ff"}], "compute": [], "storage": []}},
             "desc": "macAddress (WIRED mac) is mandatory. Returns 202 + Location async-operations/{id}."},
            {"name": "Poll async-operation", "method": "GET",
             "url": "{{glp_base}}/devices/v1/async-operations/{{op_id}}",
             "headers": {"Authorization": "Bearer {{glp_token}}"}, "body": None},
            {"name": "List subscriptions", "method": "GET",
             "url": "{{glp_base}}/subscriptions/v1/subscriptions?limit=100&offset=0",
             "headers": {"Authorization": "Bearer {{glp_token}}"}, "body": None},
            {"name": "List Central app instances", "method": "GET",
             "url": "{{glp_base}}/service-catalog/v1/service-manager-provisions",
             "headers": {"Authorization": "Bearer {{glp_token}}"}, "body": None,
             "desc": "Fallback /service-catalog/v1beta1/service-manager-provisions. Gives id + region."},
            {"name": "Assign app + region (step 1 of 2)", "method": "PATCH",
             "url": "{{glp_base}}/devices/v2beta1/devices?id={{device_uuid}}",
             "headers": {"Authorization": "Bearer {{glp_token}}", "Content-Type": "application/merge-patch+json"},
             "body": {"mode": "raw", "data": {"application": {"id": "{{app_id}}"}, "region": "us-west"}}},
            {"name": "Assign subscription (step 2 of 2)", "method": "PATCH",
             "url": "{{glp_base}}/devices/v2beta1/devices?id={{device_uuid}}",
             "headers": {"Authorization": "Bearer {{glp_token}}", "Content-Type": "application/merge-patch+json"},
             "body": {"mode": "raw", "data": {"subscription": [{"id": "{{subscription_uuid}}"}]}},
             "desc": "Separate PATCH — GLP rejects combining app + subscription."},
        ],
    },
    {
        "name": "Classic Central",
        "blurb": "API gateway path (Classic destinations + hybrid moves). Bearer "
                 "{{classic_token}}; refresh-token params go in the QUERY STRING.",
        "requests": [
            {"name": "Refresh token (rotates!)", "method": "POST",
             "url": "{{classic_base}}/oauth2/token?client_id={{client_id}}&client_secret={{client_secret}}&grant_type=refresh_token&refresh_token={{classic_refresh_token}}",
             "headers": {}, "body": None,
             "desc": "Empty body; the response refresh_token is NEW (single-use) — save it."},
            {"name": "List groups", "method": "GET",
             "url": "{{classic_base}}/configuration/v2/groups?offset=0&limit=20",
             "headers": {"Authorization": "Bearer {{classic_token}}"}, "body": None},
            {"name": "List sites", "method": "GET",
             "url": "{{classic_base}}/central/v2/sites?offset=0&limit=100&calculate_total=true",
             "headers": {"Authorization": "Bearer {{classic_token}}"}, "body": None},
            {"name": "List monitored APs", "method": "GET",
             "url": "{{classic_base}}/monitoring/v2/aps?limit=100&calculate_total=true",
             "headers": {"Authorization": "Bearer {{classic_token}}"}, "body": None},
            {"name": "Move devices into group (hybrid)", "method": "POST",
             "url": "{{classic_base}}/configuration/v1/devices/move",
             "headers": {"Authorization": "Bearer {{classic_token}}"},
             "body": {"mode": "raw", "data": {"group": "{{group}}", "serials": ["{{serial}}"]}}},
            {"name": "Create WLAN (full_wlan)", "method": "POST",
             "url": "{{classic_base}}/configuration/full_wlan/{{group}}/{{ssid_name}}",
             "headers": {"Authorization": "Bearer {{classic_token}}"},
             "body": {"mode": "raw", "data": {"value": "<wlan + access_rule JSON, stringified>"}}},
        ],
    },
]
